name: "My First Workflow"

on:
    push:
        branches:
            - master
            - production
    
    pull_request:
        branches:
            - master
        types:
            - closed

jobs:
    on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "push log"
              run: echo "pushed on master branch"

            - name: "Print current time"
              run: date

    on-pull-request:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "pull log"
              run: echo "pull request to master"

    on-pull-request-closed:
        if: github.event_name == 'pull_request' && github.action.type == 'closed'
        runs-on: ubuntu-latest
        steps:
            - name: "pull closed"
              run: echo "pull request closed"
